const CATEGORIES = [
  {id:'silk',label:'Silk Sarees',img:'images/cat-silk.jpg'},
  {id:'cotton',label:'Cotton Sarees',img:'images/cat-cotton.jpg'},
  {id:'linen',label:'Linen Sarees',img:'images/cat-linen.jpg'},
  {id:'festive',label:'Festive Collection',img:'images/cat-festive.jpg'},
  {id:'wedding',label:'Wedding Collection',img:'images/cat-wedding.jpg'}
];

const PRODUCTS = [
  {id:'p1',name:'Amaya Banarasi Silk',category:'silk',price:18900,mrp:24500,
   images:['images/p1-1.jpg','images/p1-2.jpg'],
   fabric:'Pure Banarasi Silk',blouse:'Unstitched, matching',length:'6.3m + 0.8m blouse',
   desc:'Woven on traditional handlooms, Amaya carries a rich zari border and a fine gold buti scattered across a deep silk body — the kind of saree that anchors a wedding wardrobe.'},
  {id:'p2',name:'Meher Lavender Organza',category:'festive',price:14200,mrp:null,
   images:['images/p2-1.jpg','images/p2-2.jpg'],
   fabric:'Silk Organza',blouse:'Unstitched, contrast',length:'6.3m + 0.8m blouse',
   desc:'A featherlight organza in soft lavender, hand-embroidered along the border. Made for festive daytime occasions where you want elegance without weight.'},
  {id:'p3',name:'Ishaani Champagne Tissue',category:'silk',price:21500,mrp:null,
   images:['images/p3-1.jpg','images/p3-2.jpg'],
   fabric:'Tissue Silk',blouse:'Unstitched, matching',length:'6.3m + 0.8m blouse',
   desc:'Champagne-gold tissue silk with a subtle sheen that shifts in the light. Minimal embellishment, maximum drape — quiet luxury for evening events.'},
  {id:'p4',name:'Noor Ivory Handloom Cotton',category:'cotton',price:6800,mrp:null,
   images:['images/p4-1.jpg','images/p4-2.jpg'],
   fabric:'Handloom Cotton',blouse:'Unstitched, matching',length:'5.8m + 0.8m blouse',
   desc:'A breathable ivory handloom cotton with a fine woven border. Easy to drape, easy to wear all day — everyday elegance done right.'},
  {id:'p5',name:'Kavya Rose Gold Kanjeevaram',category:'silk',price:23800,mrp:29900,
   images:['images/p5-1.jpg','images/p5-2.jpg'],fabric:'Kanjeevaram Silk',blouse:'Unstitched, contrast',length:'6.3m + 0.8m blouse',
   desc:'Temple-border Kanjeevaram in rose gold, woven for occasions that call for real heritage silk.'},
  {id:'p6',name:'Sitara Emerald Linen',category:'linen',price:5200,mrp:null,
   images:['images/p6-1.jpg','images/p6-2.jpg'],fabric:'Pure Linen',blouse:'Unstitched, matching',length:'5.8m + 0.8m blouse',
   desc:'A crisp emerald linen with a soft fall, perfect for work-day elegance and warm afternoons.'},
  {id:'p7',name:'Ritika Blush Chiffon',category:'festive',price:9600,mrp:12500,
   images:['images/p7-1.jpg','images/p7-2.jpg'],fabric:'Georgette Chiffon',blouse:'Unstitched, matching',length:'6.0m + 0.8m blouse',
   desc:'Airy blush chiffon with delicate sequin work along the border — light enough to move all evening.'},
  {id:'p8',name:'Tanvi Coral Cotton Silk',category:'cotton',price:7400,mrp:null,
   images:['images/p8-1.jpg','images/p8-2.jpg'],fabric:'Cotton Silk Blend',blouse:'Unstitched, matching',length:'5.8m + 0.8m blouse',
   desc:'A coral cotton-silk blend that holds its shape beautifully — office-ready, evening-ready.'},
  {id:'p9',name:'Anaya Midnight Tussar',category:'silk',price:16900,mrp:null,
   images:['images/p9-1.jpg','images/p9-2.jpg'],fabric:'Tussar Silk',blouse:'Unstitched, contrast',length:'6.3m + 0.8m blouse',
   desc:'Deep midnight tussar with a soft sheen and hand-painted motifs along the pallu.'},
  {id:'p10',name:'Vaani Ivory Linen',category:'linen',price:5800,mrp:null,
   images:['images/p10-1.jpg','images/p10-2.jpg'],fabric:'Pure Linen',blouse:'Unstitched, matching',length:'5.8m + 0.8m blouse',
   desc:'Clean ivory linen with a thin gold edge — minimal, breathable, endlessly wearable.'},
  {id:'p11',name:'Diya Maroon Banarasi',category:'wedding',price:27500,mrp:33900,
   images:['images/p11-1.jpg','images/p11-2.jpg'],fabric:'Banarasi Silk',blouse:'Unstitched, contrast',length:'6.3m + 0.8m blouse',
   desc:'A bridal-weight maroon Banarasi with dense zari work — made for the big occasions.'},
  {id:'p12',name:'Naina Peach Organza',category:'festive',price:11200,mrp:null,
   images:['images/p12-1.jpg','images/p12-2.jpg'],fabric:'Silk Organza',blouse:'Unstitched, matching',length:'6.3m + 0.8m blouse',
   desc:'Soft peach organza with scattered floral embroidery, light enough for daytime festivities.'},
  {id:'p13',name:'Riya Sand Handloom Cotton',category:'cotton',price:6200,mrp:null,
   images:['images/p13-1.jpg','images/p13-2.jpg'],fabric:'Handloom Cotton',blouse:'Unstitched, matching',length:'5.8m + 0.8m blouse',
   desc:'Warm sand-toned handloom cotton with a narrow woven border — an everyday staple.'},
  {id:'p14',name:'Ishita Gold Kanjeevaram',category:'wedding',price:25900,mrp:null,
   images:['images/p14-1.jpg','images/p14-2.jpg'],fabric:'Kanjeevaram Silk',blouse:'Unstitched, contrast',length:'6.3m + 0.8m blouse',
   desc:'Classic gold-and-maroon Kanjeevaram with a wide temple border — timeless bridal party wear.'}
];

function getProduct(id){ return PRODUCTS.find(p => p.id === id); }
